### ISSUE TITLE
refactor code consistency

### ISSUE THREAD

**Issue by ipapandinas** [capsule-corp-ternoa/ternoa-js#107]
Some cleaning have to be done to improve the code consistency:

- [x] use `BalanceType` for `BN` on types
- [x] rename _index.test.ts_ into _extrinsics.test.ts_
- [x] remove I from types names (e.g. `INftState` becomes `NftStateType`)
- [x] rename all underscore cases into camel cases

**Comment by Victor-Salomon** [comment]
BN for in extrinsics' parameters will not be changed in the 1.4.0Alpha. Isn't it confusing fir end user to ask for a BalanceType ? expecting a BN can not be confusing for non used to BN users?

**Comment by ipapandinas** [comment]
IMO `BalanceType` is more confusing. `BN` stands for Big Number, it will be easy to get familiar with for non experimented users.

Moreover they are already a lot of documentation using `BN` (e.g. [Working with numbers](https://polkadot.js.org/docs/api/start/types.basics#working-with-numbers) from the Polkadot API doc)

Polkadot API uses `BN` in its [polkadot/utils](https://github.com/polkadot-js/common/blob/master/packages/util/src/bn/bn.ts) packages.

Let's remove `BalanceType` type ✌️
