### ISSUE TITLE
Error messages are not standardized 

### ISSUE THREAD

**Issue by markopoloparadox** [capsule-corp-ternoa/ternoa-js#11]
I wanted to test out what kind of error messages do we get when something fails and it seems that the error messages are not properly standardized. Instead of returning a random text message it would make more sense to return the actual error code.

Example (invalid collection ID when calling createNft):
**Actual message**: No data retrieved for the collectionId : 101010
**Expected message**: CollectionNotFound

Minimal Example:
```ts
import '@polkadot/api-augment';
import { createNft, getKeyringFromSeed } from 'ternoa-js';

async function main() {
    let keyring = await getKeyringFromSeed("//TernoaTestAccount");
    try {
        let a = await createNft("Test", 0, 101010, undefined, keyring, undefined);
    } catch (error: any) {
        console.log(error);
    }
    process.exit();
}
main();
```
![image](https://user-images.githubusercontent.com/4882434/176426884-075765dc-14ec-4e1e-8e50-cbcaf020f5b2.png)

**Comment by Leouarz** [comment]
Actually, this should not even be handled by us. the error should occur when the transaction is submitted.

**Comment by ipapandinas** [comment]
It was designed in this way to avoid spending fees. But I am agreed we can remove those checks and used chain error messages to avoid useless chain overload.
