### ISSUE TITLE
Mixing null and unefined

### ISSUE THREAD

**Issue by markopoloparadox** [capsule-corp-ternoa/ternoa-js#12]
Maybe it would make more sense to just use one "optional" type instead of two.
It feels weird that I need to use both `null` and `undefined` on the same interface.
![image](https://user-images.githubusercontent.com/4882434/176431744-ed3966d9-8f1e-486b-9c14-3ace6b0a211c.png)

**Comment by Leouarz** [comment]
Yeah I see what you mean. I guess the confusion comes from the parameters of the createNft call in the chain. I guess it would also work with undefined for nftCollectionId.
@ipapandinas
