### ISSUE TITLE
CreateNFT function may not create an NFT

### ISSUE THREAD

**Issue by markopoloparadox** [capsule-corp-ternoa/ternoa-js#13]
As far as I can see, the `createNFT` function does not wait for the block to be finalized. This can cause problems when forks happen (and they happen quite often) because then the tx hash that was generated is not valid anymore.

This is a major issue and should be dealt with asap.

**Comment by markopoloparadox** [comment]
@mohsinriaz17 Can confirm that this happens.

**Comment by Leouarz** [comment]
createNFT behave differently depending on if it can be executed or not.
The createNFT hash does not correspond to a hash on chain. It correspond to an unsigned transaction that can be signed by anyone.

It's up to the user to sign the hash, submit it and watch the callback. Like polkadot-js

**Comment by markopoloparadox** [comment]
That's only the case when you don't pass a keyring

**Comment by ipapandinas** [comment]
What do you mean by forks ?
In our actual architecture, it depends on the user to provide a callback to track the extrinsic progress when a keyring is used too. Why **nfts.create** would be different from other extrinsics ?

**Comment by markopoloparadox** [comment]
Your question is valid and I have discussed with Ghali today.
The conclusion is that it would be beneficial to provide two similar but different interfaces to our users. One would just create the unsigned and unsubmited TX hash which then the user needs to manage and one interface would do everything for the users and return a CollectionEvent object (or CreateNFTEvent object).

Here is the reasoning:

### Reason to provide a CreateNFTTX interface
In most (if not all of them) production cases the signing, submiting and creating phase of a transaction is separated into multiple layers(or modules) of code. This basically means that the consumer needs to handle everything on their side (including the callback). A way how we can help him to do his job easier is to provide helper structures and helper functions.  This function would showcase how elegant and flexible our API is.

### Reason to provide a CreateNFT interface
This interface is different from CreateNFTTx in that way that the result of this call is either a CreateNFTEvent object or an error. This means that the consumer doesn't need to spend hours in figuring out how to properly write a callback and instead he can call this functions and everything is done for him. This function would showcase how convenient our API is.

With both interfaces(functions) available to the user, we can without any problem say that our API is elegant, conviniet and at the same time as flexible as it can get.

**Comment by markopoloparadox** [comment]
To clarify the "fork" thing. When you call the Polkadot or our API, you can request for an extrinsics to be signed and submitted and in return you get an signed-submitted(SS) transaction hash. Now the problem with that SS transaction hash is that it cannot be trusted if the caller didn't wait for the TX to be included inside a finalized block. Forks (like literal blockchain forks) happen quite a lot in systems that use BABE and GRANDPA (which we use). 

Now if you have a SS transaction hash from a block that was discarded by GRANDPA, you kinda are in a bad place since that SS transaction hash is not valid anymore.
