### ISSUE TITLE
Unoptimal call execution may hammer our public nodes

### ISSUE THREAD

**Issue by markopoloparadox** [capsule-corp-ternoa/ternoa-js#14]
Whenever you do a query you are contacting a public node to get some information. Too many queries can hammer our node and make it unresponsive.

Example:
In `createNFT` you you make two calls that are unnecessary. (`checkBalanceToMintNft` and `getCollectionData`). They cause more harm than good and here are the problems:
- The user isn't aware that you do additional unnecessary calls
- Those unnecessary calls slow down the execution of the `createNFT` function
- Those unnecessary calls hammer our public nodes

![image](https://user-images.githubusercontent.com/4882434/176435512-1cc6409e-bad5-4d75-af3b-279515503b1c.png)

**Comment by Leouarz** [comment]
Agreed on one of the point.
We shouldn't check that much stuff. It should be up to the user to call the correct function after checking it's valid.

Concerning the queries to the chain, it can indeed be a problem but isn't it the same for polkadot js / ui ?
