### ISSUE TITLE
[Secret NFTs] SGX pallet health status before minting secret

### ISSUE THREAD

**Issue by Victor-Salomon** [capsule-corp-ternoa/ternoa-js#151]
### Is your feature request related to a problem? Please describe.

Checker: Can I mint a Secret? => at least 1 cluster full on-chain + /health check request on all enclaves of the cluster.

### Describe the solution you'd like

 Returns a boolean if the NFT can be minted ? 
 Isolate the function as it's not needed to do it each time (in case of batch it needs to do it just one).

### Describe alternatives you've considered

-

**Comment by ipapandinas** [comment]
Resolved in #141
