### ISSUE TITLE
Hash no working on Ternoa explorer

### ISSUE THREAD

**Issue by Nzenou** [capsule-corp-ternoa/ternoa-js#154]
### Describe the bug

Hello, 

I am using the code below, to transfer Caps for customers the only problem is that the hash that I receive is not working on the Ternoa explorer, I have no results when I search with the hash of the transaction, but I can find the transaction by searching with my wallet address and looking for it in Extrinsics section. 
 
Is it possible to get a workaround to directly have the good hash? 

Thanks in advance 

### To reproduce

use the submitTxHash

### Expected behavior

receive a hash that is not recognized 

### Screenshots

<img width="799" alt="Capture d’écran 2023-01-31 à 18 58 05" src="https://user-images.githubusercontent.com/44473759/215728290-5aed10c1-a74f-4402-bd34-48ca94ceca70.png">

**Comment by ipapandinas** [comment]
hello @Nzenou 🙋‍♂️
