### ISSUE TITLE
Connection mobile 

### ISSUE THREAD

**Issue by Nzenou** [capsule-corp-ternoa/ternoa-js#156]
### Describe the bug

Hello, 

how a customer can access to my Dapp with is mobile but don’t have brave on his phone ? 

### To reproduce

..

### Expected behavior

…

**Comment by Victor-Salomon** [comment]
Hello @Nzenou, 
The used browser is not that important (your dApp needs to be compatible with Safari, Google(...)), as in the end, you should connect to Ternoa wallet, directly of through a deeplink to Ternoa wallet. 

We do not have any documentation on it yet from SDK. You can have a look at the flow used by https://secret-stash.io/.

**Comment by Nzenou** [comment]
Hello @Victor-Salomon 
Thanks for this quick answer 
how can I create the deeplink to Ternoa wallet 
Thanks in advance

**Comment by Victor-Salomon** [comment]
Hello @Nzenou, 
We are currently rewriting the official [Ternoa Doc](https://docs.ternoa.network/) and provide incremental updates. 
The wallet connection is not implemented yet, but I can recommand to look at our short wallet demo/tuto repo [here](https://github.com/capsule-corp-ternoa/ternoa-wallet). Feel free to open a discussion on the repo or come back to us if you need anything. 👋
