### ISSUE TITLE
BatchInterruptedEvent : Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by Evild67** [capsule-corp-ternoa/ternoa-js#56]
I tried to trigger a BatchInterruptedEvent and got an error from the SDK

![CleanShot 2022-07-19 at 16 16 29](https://user-images.githubusercontent.com/2675980/179774451-37a64a25-0b51-419d-9ccf-1f30980294e2.png)

**File : src/events.ts**
```
export class BatchInterruptedEvent extends BlockchainEvent {
[...]
  constructor(event: Event) {
    super(event, EventType.BatchInterrupted)

    this.index = Number.parseInt(event.data[0].toString())
    this.error = event.data[1].toJSON() as {
      module: {
        index: number
        error: string
      }
    }
    this.errorType = event.data[2].toString() // event.data[2] is undefined
    this.details = event.data[3].toString() // event.data[3] is undefined
  }
}
```

The data is displayed correctly on Polkadot.js.org/apps
![CleanShot 2022-07-19 at 16 25 40](https://user-images.githubusercontent.com/2675980/179774787-1d719945-3562-446d-9fdc-7a4da9112598.png)

**Comment by ipapandinas** [comment]
Hi,
thank you for this feedback. This issue is solved in the next release candidate: [v1.2.0-rc0](https://github.com/capsule-corp-ternoa/ternoa-js/releases/tag/v1.2.0-rc0).
Sorry for the late response.
