### ISSUE TITLE
"Events" wiki section

### ISSUE THREAD

**Issue by markopoloparadox** [capsule-corp-ternoa/ternoa-js#64]
> Marko original idea:
> 
> Short example that explains what blockchain events are and how they can be captured using our SDK.
> 
> Use the same ts and js config as the Starter Project example.

This section detailed Events:
- [x] overview of what are chain events
- [x] design choices regarding response format
- [x] detail of each Ternoa event available in the SDK

**Comment by Victor-Salomon** [comment]
https://github.com/capsule-corp-ternoa/ternoa-js/wiki/Events ✅
